classroom/urls.py
from django.urls import path
from .views import Thankyou,ContactFormViews,Home_view,TeacherCreateView,TeacherListView,TeacherDetailView,TeacherUpdateView,TeacherDeleteView

app_name = 'classroom'

urlpatterns = [
     path('', Home_view.as_view(), name='home'),
    path('thankyou/', Thankyou.as_view(), name='thankyou'),
    path('contact/', ContactFormViews.as_view(), name='contact'),
     path('create_teacher/', TeacherCreateView.as_view(), name='create_teacher'),
    path('teacher_list', TeacherListView.as_view(), name='teacher_list'),
   path('teacher_detail/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),
   path('delete_teacher/<int:pk>/', TeacherDeleteView.as_view(), name='delete_teacher'),
   path('update_teacher/<int:pk>/', TeacherUpdateView.as_view(), name='update_teacher')

   

  
]
    

school/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('',RedirectView.as_view(url = 'classroom/'))
    
]

classroom/models.py
from django.db import models

class Teacher(models.Model):
    first_name = models.CharField( max_length=30)
    last_name = models.CharField(max_length=30)
    subject  = models.CharField( max_length=30)


    def __str__(self):
        return f" {self.first_name} {self.last_name} is teaches {self.subject}"

classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name  = forms.CharField(max_length=30)
    message = forms.CharField(max_length=30)

    

classroom/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView,ListView,CreateView,DetailView,UpdateView,DeleteView
from .forms import ContactForm
from django.urls import reverse_lazy
from .models import Teacher

class Home_view(TemplateView):
    template_name = 'classroom/home.html'

class Thankyou(TemplateView):
    template_name = 'classroom/thankyou.html'

class ContactFormViews(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'
    
    success_url = reverse_lazy('classroom:thankyou') 

class TeacherCreateView(CreateView):
    model = Teacher
    fields = "__all__" 
    success_url = reverse_lazy('classroom:thankyou') 

   
class TeacherListView(ListView):
    model =Teacher
    template_name = "teacher_list.html"
    queryset = Teacher.objects.order_by('first_name')
    context_object_name = "teacher_list"

class TeacherDetailView(DetailView):
    model = Teacher 
    context_object_name = 'teacher'

class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:teacher_list') 

class TeacherDeleteView(DeleteView):
    model = Teacher
    
    success_url  = reverse_lazy('classroom:teacher_list')

classroom/templates/classroom/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>
    <h1>Home</h1>
    <ul>
        <li>
            <a href="{% url 'classroom:thankyou' %}">Thank you link</a>
        </li>
    <li>
            <a href="{% url 'classroom:create_teacher' %}">teacher Create View Page</a>
        </li>
        <li>
             <a href="{% url 'classroom:teacher_list' %}">teacher list View Page</a> 
        </li>
   
      
    </ul>
</body>
</html>

classroom/templates/classroom/teacher_confirm_delete.html
<h1> do you want to delete <h1>
    <form method = "POST"> 
        {% csrf_token %}
        <input type  = "submit" value = "confirm delete">
        
        
        <form>

classroom/templates/classroom/teacher_detail.html
<h1> more details of teachers <h1>
<ul>
   <li> {{teacher}} <li>
<ul> 

classroom/templates/classroom/teacher_form.html
<h1> teacher_form.html </h1>

<form method = "POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type = 'submit' value = 'submit'>
<form>

classroom/templates/classroom/teacher_list.html
<h1>teacherList <h1>  
<ul>
    {%for teacher in teacher_list %}
         <li>
              <a href="/classroom/teacher_detail/{{teacher.id}}">{{ teacher.first_name }} {{ teacher.last_name }}</a>
         <li>
            <ul> 
                <li>
                    <a href="/classroom/update_teacher/{{teacher.id}}">update information for {{teacher.first_name}}</a>
                 <li>
                 <li>
                 <a href="/classroom/delete_teacher/{{teacher.id}}">delete</a>
                 <li> 
            <ul>
    <ul>         
{% endfor %}
<ul>
    

classroom/templates/classroom/thankyou.html
<h1> THANKYOU </h1>
<ul>
    <li>
        <a href="{% url 'classroom:home' %}">back home</a>
    </li>

<ul>